### ISSUE TITLE
Browsing through function call graphs

### ISSUE THREAD

**Issue by elfring** [bootlin/elixir#10]
How do you think about to support the display and advanced navigation for [call graphs](https://en.wikipedia.org/wiki/Call_graph "Description for usages of call graphs") besides of repeated searches for a single function identifier?

**Comment by michaelopdenacker** [comment]
Hi Markus,

Thank you for this suggestion! That may be worth it to implement it, though we won't be able to do it in the immediate future. 

I propose to keep this bug open so that we can considering when we plan for a new development and improvement pass on Elixir.

To help us, would you have an example to suggest to us (I mean like a static page that you would produce by yourself... we would then consider automating it)? This would help to make decisions and get a clearer idea of what we could do...

Thanks,

Michael.

**Comment by elfring** [comment]
There are several approaches available already to handle call graphs to some degree.
Which one would you prefer for your software infrastructure?

**Comment by tleb** [comment]
The proposal would be complex to implement. It would require to be able to have a graph of function calls in the database. It wouldn't deal with function pointers and macro stuff, which are all over the place.

An alternative solution that would be much easier to implement (only front-end changes) would be a history of recently visited pages. That kind of helps with the standard usecase of starting from the main entry point and going deep into it. But that is already provided by browsers (right-click the left arrow).

So we'll go ahead and close this feature proposal.
