### ISSUE TITLE
Use of uninitialized value in find-file-doc-comments.pl line 68.

### ISSUE THREAD

**Issue by michaelopdenacker** [bootlin/elixir#102]
Hello,

Running ./update.py on a test Linux directory (set up to index just one tag), I'm getting :
...
linuxtest - docs: 64000 (100%)
linuxtest - docs: 65000 (100%)
Use of uninitialized value $source_lines[0] in pattern match (m//) at /home/mikael/elixir/find-file-doc-comments.pl line 68.
Use of uninitialized value $source_lines[0] in pattern match (m//) at /home/mikael/elixir/find-file-doc-comments.pl line 83.
linuxtest - docs: 66000 (100%)
Use of uninitialized value $source_lines[0] in pattern match (m//) at /home/mikael/elixir/find-file-doc-comments.pl line 68.
Use of uninitialized value $source_lines[0] in pattern match (m//) at /home/mikael/elixir/find-file-doc-comments.pl line 83.
linuxtest - docs: 67000 (100%)

Not critical apparently, but something may still be wrong...
Michael

**Comment by michaelopdenacker** [comment]
@cxw42 any clue ?

**Comment by cxw42** [comment]
**Question:**: In `lib.py`, should `script()` die if `script.sh` exits with a nonzero value?  Because it doesn't, `update.py` doesn't fail --- and so the tests don't fail --- even if one of the `t/*.t` files fails.

**Update:**

I was able to reproduce the problem with the input:

    void foo(void)
    {
    }

I will submit a PR with a fix.

**Comment by michaelopdenacker** [comment]
Confirming that the issue is gone. I was indexing Linux 5.6.1.
