### ISSUE TITLE
Some references are missing

### ISSUE THREAD

**Issue by jscissr** [bootlin/elixir#107]
I noticed that in some cases, not all references of an identifier are returned.

For example, the reference to `I2C_M_NO_RD_ACK` in https://elixir.bootlin.com/linux/v5.6.2/source/drivers/i2c/algos/i2c-algo-bit.c#L456 is missing in https://elixir.bootlin.com/linux/v5.6.2/ident/I2C_M_NO_RD_ACK
Interestingly, it does appear for an earlier linux version: https://elixir.bootlin.com/linux/v5.1.21/ident/I2C_M_NO_RD_ACK

**Comment by michaelopdenacker** [comment]
Hi,
Oops, this is an issue indeed!
We will investigate it.
Many thanks for reporting it (and for using Elixir!)
Cheers,
Michael.

**Comment by carmeli-tamir** [comment]
I've tried to reproduce on my machine but couldn't, update.py indexes this identifier well for version v5.6.
The problem seems to apply starting from v5.2 onward only on the website, maybe just give update.py another run on versions v5.2 onward?

Also, @michaelopdenacker I must ask after reviewing the relevant code in update.py :: updateReferences, why is the loop switching the behavior on every token? And how doesn't it loose tokens? 😕

**Comment by michaelopdenacker** [comment]
Looks fixed in version 2.0
