### ISSUE TITLE
Docker build error.

### ISSUE THREAD

**Issue by Mutated1994** [bootlin/elixir#172]
```
ctags: Unknown option: --extras
ctags: Unknown option: --kinds-c

```

FROM centos/httpd-24-centos7

**Comment by Mutated1994** [comment]
There is no problem when using the v1.0 tag.

**Comment by cxw42** [comment]
The version of ctags used by Elixir changed recently --- see, e.g., #141.  It should work if you install the latest Universal ctags.  (Sorry, I don't know enough Docker to know the specifics of the fix!)

**Comment by Mutated1994** [comment]
> The version of ctags used by Elixir changed recently --- see, e.g., #141. It should work if you install the latest Universal ctags. (Sorry, I don't know enough Docker to know the specifics of the fix!)

Thank you for your prompt reply.

**Comment by MaximeChretien** [comment]
Hi, 
Yes this problem comes from the last changes in Elixir, we use a different version of ctags to support new languages.

In order to have all capabilities of the last versions of Elixir, you need to have a version of universal-ctags built after https://github.com/universal-ctags/ctags/commit/0c78c0c4a68030df0d025c90bad291108b5e7107

I will try to update docker files but I don't know how docker works so I will need a bit of time. I will start with the debian one because we already have a prebuilt .deb binary for universal-ctags.

The centos one will require to build universal-ctags from source so it will be harder, maybe we should create a prebuilt binary (I think we need a .rpm for centos) but again I will need some time to understand how to create a .rpm, maybe someone here already knows how to do it. And I never used a distro based on rpm so I'll be happy if someone can help for that ^^

Beside that we also use a custom version of python-pygments since 2.7 is not released yet (we have a prebuilt pip .whl for that) so pygments also needs to be updated in order to have all Elixir functionalities.

**Comment by Mutated1994** [comment]
@MaximeChretien Thanks a lot bro,I really appreciate your reply.
