### ISSUE TITLE
malformed header from script 'web.py': Bad header: <p>A problem occurred in a Pyt 

### ISSUE THREAD

**Issue by Dongfang-Qu** [bootlin/elixir#213]
Visit 127.0.0.1:80/crash/latest/source in ubuntu18.04/20.04, appear the following error:

[SAT May 08 14:35:50.917756 2021] [CGID: ERROR] [PID 29463: TID 140713236875008] [Client 127.0.1:41408] malformed header The from script 'web. Py: Bad header: < p > A problem occurred in A Pyt, referer: http://127.0.0.1/crash/latest/source

**Comment by chefigor** [comment]
Try installing pygments, I did it with `pip install pygments` or you can follow their instructions  
`sudo pip3 install Pygments-2.6.1.elixir-py3-none-any.whl`

**Comment by b1cata** [comment]
I have the same problem, trying to solve for some time now. pygments installation seems to be ok:
  Requirement already satisfied: pygments in /usr/local/lib/python3.8/dist-packages (2.6.1.elixir)

I have tried on AlmaLinux 8 with python 3.6.8 and Ubuntu 20.04 with python 3.8.10
Did someone manage to solve this problem?

**Comment by neocxf** [comment]
any new updates? I recently came accross such problems too

**Comment by cxw42** [comment]
I'd like to try to repro but I don't think I have enough information.  Could someone:
* make sure all the tests pass (run `prove` in the top level);
* send me the link to the release of `crash` you are using; and
* tell me your Elixir configuration (Elixir commit, Python version, OS, `$LXR_DATA_DIR`, `$LXR_REPO_DIR`)?

Thanks!

**Comment by pickpoker** [comment]
I got the same error log in my local linux kernel project, this is my local configuration and debug info, hope it is helpful.


Software version
```
OS: Ubuntu 20.04.3 - LTS
apache: apache2-2.4.41-4ubuntu3.9
Pygments: Pygments-2.6.1.elixir-py3-none-any.whl
universal-ctags: universal-ctags_0+git20200526-0ubuntu1_amd64.deb
mod_wsgi: 4.9.0
```

The configuration process is referring to [debian dockerfile](https://github.com/bootlin/elixir/blob/master/docker/debian/Dockerfile)
```  
# cat /etc/apache2/sites-available/000-default.conf
<Directory /usr/local/elixir/http/>
    Options +ExecCGI
    AllowOverride None
    Require all granted
    SetEnv PYTHONIOENCODING utf-8
    SetEnv LXR_PROJ_DIR /srv/elixir-data
</Directory>
<Directory /usr/local/elixir/api/>
    SetHandler wsgi-script
    Require all granted
    SetEnv PYTHONIOENCODING utf-8
    SetEnv LXR_PROJ_DIR /srv/elixir-data
</Directory>
AddHandler cgi-script .py
<VirtualHost *:80>
    ServerName MY_LOCAL_IP
    DocumentRoot /usr/local/elixir/http
    WSGIScriptAlias /api /usr/local/elixir/api/api.py
    AllowEncodedSlashes On
    RewriteEngine on
    RewriteRule "^/$" "/linux/latest/source" [R]
    RewriteRule "^/(?!api|acp).*/(source|ident|search)" "/web.py" [PT]
    RewriteRule "^/acp" "/autocomplete.py" [PT]
</VirtualHost>

# cat /etc/apache2/apache.conf
HttpProtocolOptions Unsafe
```

**Which url is unstable?**
* http://x.x.x.x/linux/v3.18/source/kernel/sched/core.c
  sched/core.c sometime is ok, sometime is nok.  The error log in apache is same as this issue.
* http://x.x.x.x/linux/latest/A/ident/schedule
   This url is always NOK.

Unstable url is a large page in brower, but I am not sure this issue is related to page size, this is only my  guess.

**Debug:** 
I install [Tabbed Postman](https://chrome.google.com/webstore/detail/tabbed-postman-rest-clien/coohjcphdfgbiolnekdpbcijmhambjff?hl=en-US) in Chrome, and get some debug info.

error log
```
STATUS 500 Internal Server Error
TIME 523 ms

connection →close
content-length →610
content-type →text/html; charset=iso-8859-1
date →Tue, 11 Jan 2022 06:23:08 GMT
server →Apache/2.4.41 (Ubuntu)
```

normal log 
```
STATUS 200 OK
TIME 1461 ms

connection →Keep-Alive
content-encoding →gzip
content-type →text/html;charset=utf-8
date →Tue, 11 Jan 2022 06:24:12 GMT
keep-alive →timeout=5, max=100
server →Apache/2.4.41 (Ubuntu)
transfer-encoding →chunked
vary →Accept-Encoding
```

**Comment by b1cata** [comment]
> any new updates? I recently came accross such problems too

As far as I remember, the problem solved itself after update.py finished the job (a few days).

**Comment by cxw42** [comment]
@pickpoker Thanks!  I've seen "too many values" errors during development, but not in production.

Those errors look like they come straight from the database's data.  Are you perhaps using a database you generated using an older commit of Elixir?  @michaelopdenacker There are no compatibility guarantees between Elixir versions, are there?

**Comment by pickpoker** [comment]
Elixir is latest, commit: aa34f01f35f30b5a08f9ee8947e2eecc477427d3. The datebase is generated by this version.

**Comment by anatasluo** [comment]
I met the same problem.

My running environment: fedora 35 X86_64

httpd error log:

[Fri May 06 01:09:06.362039 2022] [core:notice] [pid 1309509:tid 1309509] SELinux policy enabled; httpd running as context system_u:system_r:httpd_t:s0
[Fri May 06 01:09:06.363565 2022] [suexec:notice] [pid 1309509:tid 1309509] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using fe80::82fa:5bff:fe1a:ac81%enp5s0f2. Set the 'ServerName' directive globally to suppress this message
[Fri May 06 01:09:06.373965 2022] [lbmethod_heartbeat:notice] [pid 1309509:tid 1309509] AH02282: No slotmem from mod_heartmonitor
[Fri May 06 01:09:06.377133 2022] [mpm_event:notice] [pid 1309509:tid 1309509] AH00489: Apache/2.4.53 (Fedora Linux) mod_wsgi/4.9.0 Python/3.10 configured -- resuming normal operations
[Fri May 06 01:09:06.377165 2022] [core:notice] [pid 1309509:tid 1309509] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Fri May 06 01:09:52.084106 2022] [cgid:error] [pid 1309512:tid 1309614] [client 192.168.5.103:54499] malformed header from script 'web.py': Bad header: <p>A problem occurred in a Pyt

**Comment by anatasluo** [comment]
When I use systemd service to start httpd, I met this problem.
When I use httpd manually from the terminal, this problem disappears. 
I guess this problem is related with systemd.

**Comment by cxw42** [comment]
@anatasluo thanks!  
* Are you able to reproduce this issue consistently?
* What is the httpd command line used by systemd, and what httpd commandline did you use when you started httpd from the terminal?

I did a search for `"systemd" "malformed header"` and found [this](https://stackoverflow.com/a/23212064) mentioning an issue in `Content-Length`.  We do not appear to send a `Content-Length` header --- we could try adding one and see if that helped.  From https://github.com/bootlin/elixir/issues/213#issuecomment-1009655771, it appears `Content-Length` is being added in the failure (NOK) case --- maybe systemd is causing that header to be added, and the computation of the value is wrong.

**Comment by anatasluo** [comment]
@cxw42 
1. yes, I can reproduce it consistently
2. same command which is '/usr/sbin/httpd -DFOREGROUND'

After some modifications, I got the complete log(check it below)

This problem is related with the permission of BsdDB3.

When I disable SELinux, this problem disappears.

I need more time to find the accurate problem here.

Later this week, I think I can supply a patch to solve this problem.


The complete log:
`
DBAccessError Python 3.10.4: /usr/bin/python3 Wed May 18 02:16:30 2022 A problem occurred in a Python script. Here is the sequence of function calls leading up to the error, in the order they occurred. /usr/local/elixir/http/web.py in 133 projects.sort() 134 135 from query import query 136 137 dts_comp_support = query('dts-comp') query undefined /usr/local/elixir/query.py in 28 dts_comp_support = int(script('dts-comp')) 29 30 db = data.DB(lib.getDataDir(), readonly=True, dtscomp=dts_comp_support) 31 32 from io import BytesIO db undefined data = data.DB = lib = lib.getDataDir = readonly undefined dtscomp undefined dts_comp_support = 1 /usr/local/elixir/data.py in __init__(self=, dir='/home/anatasluo/Git/code_read/linux/data', readonly=True, dtscomp=1) 189 ro = readonly 190 191 self.vars = BsdDB(dir + '/variables.db', ro, lambda x: int(x.decode()) ) 192 # Key-value store of basic information 193 self.blob = BsdDB(dir + '/blobs.db', ro, lambda x: int(x.decode()) ) self = self.vars undefined global BsdDB = dir = '/home/anatasluo/Git/code_read/linux/data' ro = True x undefined builtinint = /usr/local/elixir/data.py in __init__(self=, filename='/home/anatasluo/Git/code_read/linux/data/variables.db', readonly=True, contentType=.>) 150 self.db = bsddb3.db.DB() 151 if readonly: 152 self.db.open(filename, flags=bsddb3.db.DB_RDONLY) 153 else: 154 self.db.open(filename, self = self.db = self.db.open = filename = '/home/anatasluo/Git/code_read/linux/data/variables.db' flags undefined global bsddb3 = bsddb3.db = bsddb3.db.DB_RDONLY = 1024 DBAccessError: (13, 'Permission denied') __cause__ = None __class__ = __context__ = None __delattr__ = __dict__ = {} __dir__ = __doc__ = None __eq__ = __format__ = __ge__ = __getattribute__ = __gt__ = __hash__ = __init__ = __init_subclass__ = __le__ = __lt__ = __module__ = 'bsddb3.db' __ne__ = __new__ = __reduce__ = __reduce_ex__ = __repr__ = __setattr__ = __setstate__ = __sizeof__ = __str__ = __subclasshook__ = __suppress_context__ = False __traceback__ = __weakref__ = None args = (13, 'Permission denied') with_traceback = The above is a description of an error in a Python program. Here is the original traceback: Traceback (most recent call last): File "/usr/local/elixir/http/web.py", line 135, in from query import query File "/usr/local/elixir/http/../query.py", line 30, in db = data.DB(lib.getDataDir(), readonly=True, dtscomp=dts_comp_support) File "/usr/local/elixir/http/../data.py", line 191, in __init__ self.vars = BsdDB(dir + '/variables.db', ro, lambda x: int(x.decode()) ) File "/usr/local/elixir/http/../data.py", line 152, in __init__ self.db.open(filename, flags=bsddb3.db.DB_RDONLY) bsddb3.db.DBAccessError: (13, 'Permission denied') /tmp/elixir-errors/tmp_e0m18rs.txt contains the description of this error.
`

**Comment by cxw42** [comment]
@anatasluo great find!

**Comment by anatasluo** [comment]
@cxw42 I have created a pull request for this issue. And it solves my problem.

Can anyone test it to see if it works for your problems? @Dongfang-Qu @neocxf @chefigor @b1cata @pickpoker
