### ISSUE TITLE
Linux kernel-internals man-pages view of the database? [Documentation] [Long term]

### ISSUE THREAD

**Issue by cxw42** [bootlin/elixir#215]
It just occurred to me that we could take the `Documented in` links for each version and render an index of the documentation pages.  This would, in essence, become a set of man pages for the kernel internals for that version \o/ .  This is just an idea --- any thoughts or interest?

**Comment by michaelopdenacker** [comment]
Hi Chris
Thanks for the suggestion !
Actually, wouldn't it be a kernel documentation issue instead, that we should address using Sphinx?
Indeed, it would be nice to have a symbol index, such as the one we have in the Yocto Project: https://docs.yoctoproject.org/genindex.html
Cheers

**Comment by cxw42** [comment]
Yes, the Yocto symbol index is the kind of thing I am thinking of.

If this could be addressed with Sphinx, that would be great!  I do not know enough Sphinx to know how.

**Comment by fstachura** [comment]
I found this https://docs.kernel.org/genindex.html
This for older versions https://www.kernel.org/doc/html/ 

I compared index for latest with what I have in my database after indexing Linux, and it seems that Elixir finds much more doccoments than what's available in genindex. I'm not sure if that's on purpose, I was unable to find an explanation.
It seems that many doccoments related to optional things are missing. For example, `ntfs_mapping_pairs_decompress`  and other prefixed with `ntfs_`, same with `nfp_` , `acpi_` , `binder_` and many others.

[Diff between a list of indexed doccoments and symbols from genindex](https://gist.github.com/fstachura/48396f32bf353d7b3c28bb9d70f82b74) (note that the database spans versions from v3.1 to v6.9.4 and I'm comparing that with the latest genindex. laziness on my part because reindexing a single Linux version will take long, but that still brings up many, many examples of symbols available in Elixir v6.11-rc4 but not in related genindex, easy to check by comparing search results from Elixir and from the genindex. I can do a proper comparison if it's necessary). 
[Code](https://gist.github.com/fstachura/d7ab03dffffe7e668230db26d5cde669)

**Comment by tleb** [comment]
I have never digged into this. There are some special `.. kernel-doc::` blocks inside `Documentation/***.rst` files that might be part of the explanation. See [`Documentation/core-api/kernel-api.rst`](https://elixir.bootlin.com/linux/v6.10.6/source/Documentation/core-api/kernel-api.rst) as example.

The preprocessor might be another part of the explanation. Take for example `clk_bulk_prepare`. Its prototype is in `include/linux/clk.h`. Most prototypes in this file are documented, but not `clk_bulk_prepare` that is behind a `#ifdef CONFIG_HAVE_CLK_PREPARE`.

Does that help?

**Comment by fstachura** [comment]
I was more trying to see if this functionality could be useful in any way. Since the index in the docs does not contain all documented symbols then maybe? But also maybe there is an actual reason why these symbols are missing.

But it's good to know that files that are supposed to be indexed have to be explicitly linked from docs.

**Comment by cxw42** [comment]
@fstachura Thanks for the research and diff!  I am revisiting this and trying to remember my thoughts from 2021 in more detail :D .  I remember I was working on documentation of custom drivers at the time.

Elixir could in theory link to the docs.kernel.org rendered view of a symbol as well as to the source code view from which that rendering is generated.  However, I'm not sure that's worthwhile.

Based on the comments above, I think this issue can be closed Will Not Do in view of the kernel's own genindex.
