### ISSUE TITLE
Web page is blank with "This file does not exist.".

### ISSUE THREAD

**Issue by BlackBird-BB** [bootlin/elixir#224]
I build it on wsl Ubunut2004, and I almost followed the whole README. Test 1 and Test 2 both passed. But the web page is blank with "This file does not exist."
By the way, The site https://elixir.bootlin.com/linux/latest/source showed the same as mine in 2022-4-12.
I'm very confued.
![image](https://user-images.githubusercontent.com/71928408/163514792-54e01d50-076e-4aa8-9ea1-87e43c15ab7b.png)

Here are my configures:
1. Project struct:
![image](https://user-images.githubusercontent.com/71928408/163515137-5ae956d1-c1be-4b5e-b6d0-cdebce36e654.png)

2. Apache2 configure
![image](https://user-images.githubusercontent.com/71928408/163515182-09f435e5-f393-4833-80ca-7ac13a7b82da.png)

3. tests
![image](https://user-images.githubusercontent.com/71928408/163515280-6a01ff4e-1615-444d-9259-63e011a9c02c.png)
![image](https://user-images.githubusercontent.com/71928408/163515291-f8d30910-ab88-43c1-bff9-004f1144d6a2.png)

**Comment by BlackBird-BB** [comment]
detail：three projects were shown, without tags and contents. Only three projects' names.

**Comment by michaelopdenacker** [comment]
Hi
We had apparently the same issue 2 days ago (on Apr. 13), because of a git vulnerability fix applied on Ubuntu.
You should find details in the Apache logs, like:

[Wed Apr 13 10:59:33.661376 2022] [cgi:error] [pid 8673] [client 10.123.242.181:57926] AH01215: fatal: unsafe repository ('/srv/elixir-data-20201221/linux/repo' is owned by someone else): /usr/local/elixir/http/[web.py](http://web.py/)
[Wed Apr 13 10:59:33.661437 2022] [cgi:error] [pid 8673] [client 10.123.242.181:57926] AH01215: To add an exception for this directory, call:: /usr/local/elixir/http/[web.py](http://web.py/)
[Wed Apr 13 10:59:33.661442 2022] [cgi:error] [pid 8673] [client 10.123.242.181:57926] AH01215: : /usr/local/elixir/http/[web.py](http://web.py/)
[Wed Apr 13 10:59:33.661500 2022] [cgi:error] [pid 8673] [client 10.123.242.181:57926] AH01215: \tgit config --global --add [safe.directory](http://safe.directory/) /srv/elixir-data-20201221/linux/repo: /usr/local/elixir/http/[web.py](http://web.py/)

The problem was that the webserver was running git queries from a user account that isn't the one used to build the database and keep it up to date. Making the "www-data" user own the database and run the periodic updates fixed our issue.

It's likely that you're having a similar problem. At least the dates coincide.

**Comment by BlackBird-BB** [comment]
> Hi We had apparently the same issue 2 days ago (on Apr. 13), because of a git vulnerability fix applied on Ubuntu. You should find details in the Apache logs, like:
> 
> [Wed Apr 13 10:59:33.661376 2022] [cgi:error] [pid 8673] [client 10.123.242.181:57926] AH01215: fatal: unsafe repository ('/srv/elixir-data-20201221/linux/repo' is owned by someone else): /usr/local/elixir/http/[web.py](http://web.py/) [Wed Apr 13 10:59:33.661437 2022] [cgi:error] [pid 8673] [client 10.123.242.181:57926] AH01215: To add an exception for this directory, call:: /usr/local/elixir/http/[web.py](http://web.py/) [Wed Apr 13 10:59:33.661442 2022] [cgi:error] [pid 8673] [client 10.123.242.181:57926] AH01215: : /usr/local/elixir/http/[web.py](http://web.py/) [Wed Apr 13 10:59:33.661500 2022] [cgi:error] [pid 8673] [client 10.123.242.181:57926] AH01215: \tgit config --global --add [safe.directory](http://safe.directory/) /srv/elixir-data-20201221/linux/repo: /usr/local/elixir/http/[web.py](http://web.py/)
> 
> The problem was that the webserver was running git queries from a user account that isn't the one used to build the database and keep it up to date. Making the "www-data" user own the database and run the periodic updates fixed our issue.
> 
> It's likely that you're having a similar problem. At least the dates coincide.

Well， It seems the same.
> blackbird@LAPTOP-7MIGHEIR ~> tail /var/log/apache2/error.log
        git config --global --add safe.directory /home/blackbird/elixir-data/musl/repo
fatal: unsafe repository ('/home/blackbird/elixir-data/qemu/repo' is owned by someone else)
To add an exception for this directory, call:

        git config --global --add safe.directory /home/blackbird/elixir-data/qemu/repo
fatal: unsafe repository ('/home/blackbird/elixir-data/qemu/repo' is owned by someone else)
To add an exception for this directory, call:

        git config --global --add safe.directory /home/blackbird/elixir-data/qemu/repo
[Fri Apr 15 17:32:49.430889 2022] [mpm_event:notice] [pid 23210:tid 139840441945152] AH00491: caught SIGTERM, shutting down

I'm working on it. Thanks  a lot.

**Comment by BlackBird-BB** [comment]
> The problem was that the webserver was running git queries from a user account that isn't the one used to build the database and keep it up to date. Making the "www-data" user own the database and run the periodic updates fixed our issue.
update what? git or the elixir project?

**Comment by michaelopdenacker** [comment]
No, no change to Elixir.
Just change the ownership of the git repositories (and database files) to make them belong to the user that runs the queries from the webserver.

**Comment by BlackBird-BB** [comment]
Solve it. Thanks!!!

**Comment by michaelopdenacker** [comment]
Glad I could help!
