### ISSUE TITLE
# define is ignored when asking for constants

### ISSUE THREAD

**Issue by qodroi** [bootlin/elixir#228]
If a constant is defined with `# define` (With a space), Elixir won't find it. This can be easily reproduce by simply asking for let's say `MAX_ARG_PAGES` in Linux and you'll see that it didn't find any definitions, even though it exists in [linux/binfmts.h](https://elixir.bootlin.com/linux/latest/source/include/linux/binfmts.h#L23). It can confuse some people.

**Comment by qodroi** [comment]
Looks like it is actually not always like that, maybe they are ignored only when defined within a struct. Anyway, I just had the need to report it.

**Comment by cxw42** [comment]
Thanks for the report!
* I confirm that https://elixir.bootlin.com/linux/v5.19/A/ident/MAX_ARG_PAGES does not show `MAX_ARG_PAGES` as a definition.
* However, the definition is listed in the "Referenced" category:
  ![image](https://user-images.githubusercontent.com/10515894/182273722-86806435-f729-42c7-87c5-87e51c68e31f.png)

I think this is probably not because of the space in `# define`.  I think it is probably universal-ctags behaviour.  In this case, `MAX_ARG_PAGES` is [in the `#else` branch of a conditional](https://elixir.bootlin.com/linux/v5.19/source/include/linux/binfmts.h#L23).  The [universal-ctags docs](https://github.com/universal-ctags/ctags/blob/899c9f485c292bfc58231b282fc5ff1bd70b165c/docs/man/ctags.1.rst#notes-for-cc-parser) say that ctags generally follows the `#if` branch of the conditional, which does not have the definition of `MAX_ARG_PAGES`.

**Comment by qodroi** [comment]
Oh. Nice find (:

**Comment by michaelopdenacker** [comment]
Thanks for the analysis, Chris, and thanks qodroi for reporting this anyway!
