### ISSUE TITLE
script.sh: Can't find repository

### ISSUE THREAD

**Issue by gvrose8192** [bootlin/elixir#285]
Greetings.

I'm new to this and I'm trying to use this tool with a private project and I'm encountering the following error:
[Tue May 28 08:31:04.184737 2024] [wsgi:error] [pid 6803:tid 6913] [client 127.0.0.1:33298] 2024-05-28 08:31:04 [FALCON] [ERROR] GET /ident/kernel-src-git/cdev?version=latest&family=C => Traceback (most recent call last):
[Tue May 28 08:31:04.184786 2024] [wsgi:error] [pid 6803:tid 6913] [client 127.0.0.1:33298]   File "falcon/app.py", line 365, in falcon.app.App.__call__
[Tue May 28 08:31:04.184790 2024] [wsgi:error] [pid 6803:tid 6913] [client 127.0.0.1:33298]   File "/usr/local/elixir/api/api.py", line 44, in on_get
[Tue May 28 08:31:04.184793 2024] [wsgi:error] [pid 6803:tid 6913] [client 127.0.0.1:33298]     q = query.Query(data_dir, repo_dir)
[Tue May 28 08:31:04.184796 2024] [wsgi:error] [pid 6803:tid 6913] [client 127.0.0.1:33298]   File "/usr/local/elixir/api/../query.py", line 50, in __init__
[Tue May 28 08:31:04.184798 2024] [wsgi:error] [pid 6803:tid 6913] [client 127.0.0.1:33298]     self.dts_comp_support = int(self.script('dts-comp'))
[Tue May 28 08:31:04.184802 2024] [wsgi:error] [pid 6803:tid 6913] [client 127.0.0.1:33298] ValueError: invalid literal for int() with base 10: b"/usr/local/elixir/script.sh: Can't find repository\\n"
[Tue May 28 08:31:04.184806 2024] [wsgi:error] [pid 6803:tid 6913] [client 127.0.0.1:33298] 

The update.py step finished successfully with no errors - the LXR_REPO_DIR, LXR_DATA_DIR  and LXR_PROJ_DIR settings are all correct SFAICT.  I'm stumped why it can't seem to find the repo.

Any pointers or tips are appreciated!
Thanks,
Greg

**Comment by fstachura** [comment]
Hello, 

the "Can't find repository" error is most likely printed because whatever LXR_REPO_DIR is set to during the request is not an actual directory (or the web server process does not have access to that directory). script.sh is executed from the api and cgi scripts. 
https://github.com/bootlin/elixir/blob/master/script.sh#L23 
In your case, it looks like the error happens when you make a request to the API (i.e. you have clicked on an identifier from the source code view). The LXR_REPO_DIR env var is set based on the LXR_PROJ_DIR env var, which is set from the Apache configuration (at least in our Docker images and in the standard configuration described in the README).
https://github.com/bootlin/elixir/blob/master/README.adoc#configure-httpd

Did you set up Elixir by following instructions from README.md or are you using the Dockerfile?
You can open the source code and directory tree views just fine, is that correct? This would mean that this is an issue with the API/WSGI configuration.
If you are using Apache, please make sure that values of `SetEnv LXR_PROJ_DIR` in both `<Directory /usr/local/elixir/api/>` and `<Directory /usr/local/elixir/http/>` are set to the path of the directory that contains project directories (that each contain the `repo` and `data` directories). For example:

```
root@59111654872e:/# cat etc/apache2/sites-enabled/000-default.conf | head -n12
<Directory /usr/local/elixir/http/>
    Options +ExecCGI
    AllowOverride None
    Require all granted
    SetEnv PYTHONIOENCODING utf-8
    SetEnv LXR_PROJ_DIR /srv/elixir-data
</Directory>
<Directory /usr/local/elixir/api/>
    SetHandler wsgi-script
    Require all granted
    SetEnv PYTHONIOENCODING utf-8
    SetEnv LXR_PROJ_DIR /srv/elixir-data
root@59111654872e:/# ls /srv/elixir-data/
linux  musl
root@59111654872e:/# ls /srv/elixir-data/*
/srv/elixir-data/linux:
data  repo

/srv/elixir-data/musl:
data  repo
```

**Comment by gvrose8192** [comment]
Let me go through and double check the recipe considering your comments.  Thank you!

**Comment by gvrose8192** [comment]
It's probably SELinux - or that's my current theory - when I get the chance to reboot the machine I'll disable it and see how it goes.

**Comment by tleb** [comment]
Cleaning up issues and this looks like it can be closed. Feel free to discuss here if you are still facing issues!
