### ISSUE TITLE
[Zephyr] v2.1-rc1 is not indexed

### ISSUE THREAD

**Issue by abrodkin** [bootlin/elixir#75]
Zephyr v2.1-rc1 was cut 2 weeks ago yet there's no entry for it in Zephyr section of the Elixir: https://elixir.bootlin.com/zephyr/latest/source.

**Comment by michaelopdenacker** [comment]
Hi Alexey,
Many thanks for this bug report!
It allowed me to discover that we were not fetching all tags, causing some releases to be missed.
That's now fixed by https://github.com/bootlin/elixir/commit/11ed7b7684e8f514f3d0c917c78efde54609e520

Many thanks again. Several projects were impacted.
Please send us more like this one :)
Cheers,
Michael.

**Comment by abrodkin** [comment]
Sure, I'll keep you guys posted :)
But I hope with time more and more things will just work.

Thanks for the prompt fix anyways!
