### ISSUE TITLE
italics never ends after #if 0

### ISSUE THREAD

**Issue by JuliaLawall** [bootlin/elixir#76]
https://elixir.bootlin.com/linux/latest/source/kernel/cred.c#L434

There is an #if 0 on line 19 and and #else and #endif after that.  I guess that the italics is due to the #if 0, but it should stop after the #else, or at least after the #endif.

**Comment by JuliaLawall** [comment]
Here is another example, actually starting from line 604:

https://elixir.bootlin.com/linux/latest/source/drivers/scsi/mesh.c#L1847

**Comment by michaelopdenacker** [comment]
Hi Julia,
Many thanks for reporting this issue :)
Indeed, Pygments identifies code starting with #if 0 as comments (which is right), but then never closes the comments afterwards.
Therefore, the whole code that follows is considered as comments, hence the italic style.
I don't see this when I process the original code with Pygmentize, so I guess the issue comes from interference with the markers we insert.
Investigating...

**Comment by michaelopdenacker** [comment]
Got it: the "#endif" statement closing the comment was considered by our scripts as an identifier, and therefore was wrapped by some of our markers, making "#endif" unrecognizable by Pygments.
This is a more global issue as "else" and "endif"  after "#" were treated as symbols.
Blacklisting such words as symbols seems to solve the issue.
